language: java
before_install: ant init-ivy
install: 
- ant resolve
- echo ${TRAVIS_BUILD_DIR}
script: 
- ant EIDPCoreApp_Dist
- ls dist
jdk:
  - oraclejdk7
notifications:
  email: false
deploy:
  provider: releases
  api-key: "39258d95274362cbfe882c8f3044c5f41c07944b"
  file: "dist/EIDPCoreApp3.ear"
  skip_cleanup: true
  on:
    tags: true
    branch: master
