language: java
before_install: ant init-ivy
install: 
- ant resolve
script: 
- ant EIDPCoreApp_Dist
- ls dist
jdk: 
- oraclejdk7
notifications: 
  email: false
language: ruby
rvm:
- 2.0.0
before_deploy: 
- ls dist
- cp dist/EIDPCoreApp3.ear .
- cp dist/EIDPCore3.jar .
- cp dist/EIDPLib.jar .
- ls
deploy: 
  provider: releases
  api_key: 
  - secure: "v8JEqNkQIp5/f4Ddyj4AXXIVUpiNDKO8XPxWx+CDshbRkEnFvQTv20OVvWyieapp/4bLZqJ7K1Bp4uU6ka+9sigD01ASxB1p7/HtkOnNIDhyTPwbIoXy/zYiqGzciSiuPMsaLYY9wC9VrPqYyu/SzP4oHQe+Js0TW9uxVb0bxno="
  file: 
  - EIDPLib.jar
  - EIDPCoreApp3.ear
  - EIDPCore3.jar
  skip_cleanup: true
  on: 
    tags: true
    branch: master
    repo: UCL/EIDP
after_deploy:
- ls
