sudo: false
language: java
before_install: ant init-ivy
install: 
- ant resolve
script: 
- ant EIDPCoreApp_Dist
- ls dist
jdk: 
- oraclejdk7
notifications: 
  email: 
  - d.guzman@ucl.ac.uk
after_success: 
- cp dist/EIDPCoreApp3.ear .
- cp dist/EIDPDataNode3.ear .
- ls
- chmod +x travis/github-release.sh
- travis/github-release.sh "$TRAVIS_REPO_SLUG" "$(git describe)" EIDP*.?ar
env: 
  matrix: 
    secure: CXU0POvIYf27nxJxpsVocrAQHHTav6l5hC6c5AXnDIJRyN0XtZTmqYkWqsN0zRZ5rrtW9965+Hb29YGwF04rF8hW3JTjncI78w+ouh7thjbOln5mdW71HkMJ7Hb2hDF1LFOBeSREyg+8CL4RQoa335lRo5vWvacc3kOm1x6o4yc=
