language: java
before_install: ant init-ivy
install: 
- ant resolve
script: 
- ant EIDPCoreApp_Dist
- ls dist
jdk: 
- oraclejdk7
notifications: 
  email: false
before_deploy: 
- ls dist
deploy: 
  provider: releases
  api_key: 
    secure: v8JEqNkQIp5/f4Ddyj4AXXIVUpiNDKO8XPxWx+CDshbRkEnFvQTv20OVvWyieapp/4bLZqJ7K1Bp4uU6ka+9sigD01ASxB1p7/HtkOnNIDhyTPwbIoXy/zYiqGzciSiuPMsaLYY9wC9VrPqYyu/SzP4oHQe+Js0TW9uxVb0bxno=
  file: dist/EIDPCoreApp3.ear
  "on": 
    tags: true
    repo: UCL/EIDP
after_deploy:
- ls dist
